// Run with mise exec -- node e2e/web-smoke.mjs /absolute/path/to/playwright/index.mjs
// Playwright is a test-only dependency installed outside this Go repository.
import {spawn} from 'node:child_process';
import {mkdtemp, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const {chromium} = await import(pathToFileURL(process.argv[2]).href);
const artifacts = await mkdtemp(join(tmpdir(), 'lampi-browser-evidence-'));
const buildDir = await mkdtemp(join(tmpdir(), 'lampi-browser-build-'));
const binary = join(buildDir, 'fixture');
const build = spawn('go', ['build', '-buildvcs=false', '-o', binary, './internal/web/smoketest'], {stdio: 'inherit'});
await new Promise((resolve, reject) => build.on('exit', code => code === 0 ? resolve() : reject(new Error('fixture build failed'))));
const processes = [];
async function fixture(args = []) {
  const proc = spawn(binary, args, {stdio: ['ignore', 'pipe', 'inherit']});
  processes.push(proc);
  return await new Promise((resolve, reject) => {
    let out = '';
    const timer = setTimeout(() => reject(new Error('fixture startup timed out')), 30000);
    proc.stdout.on('data', data => { out += data; if (out.includes('\n')) { clearTimeout(timer); resolve(JSON.parse(out.split('\n')[0])); } });
    proc.on('exit', code => {clearTimeout(timer); reject(new Error(`fixture exited ${code}`));});
  });
}
let browser;
try {
  browser = await chromium.launch({headless: true});
  const live = await fixture();
  const context = await browser.newContext({ignoreHTTPSErrors: true, viewport: {width: 1440, height: 1100}});
  const page = await context.newPage();
  page.setDefaultTimeout(10000);
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(live.url);
  await page.getByRole('heading', {name: 'A view into your lake.'}).waitFor();
  assert.equal(await page.locator('.stats article').first().locator('strong').innerText(), '123');
  assert.equal(await page.evaluate(() => window.owned), undefined);
  await page.screenshot({path: join(artifacts, 'overview-desktop.png'), fullPage: true});
  await page.getByRole('navigation', {name: 'Main navigation'}).getByRole('link', {name: 'Sessions', exact: true}).click();
  assert.equal(await page.locator('tbody tr').count(), 50);
  await page.getByRole('link', {name: 'Next page'}).first().click();
  assert.equal(await page.locator('body').getAttribute('data-poll'), 'false');
  assert.equal(await page.locator('select[name=harness]').count(), 1, (await page.locator('body').innerText()).slice(0,1000));
  await page.getByLabel('Harness', {exact: true}).selectOption('codex');
  await page.getByRole('button', {name: 'Apply filters'}).click();
  assert.equal(await page.locator('tbody tr').count(), 21);
  assert.match(await page.locator('tbody tr').first().innerText(), /codex/);
  await page.getByRole('link', {name: 'Clear', exact: true}).click();
  await page.locator('.session-name').first().click();
  await page.getByRole('heading', {name: 'Session details', exact: true}).waitFor();
  await page.getByRole('link', {name: 'Provenance', exact: true}).click();
  assert.match(await page.locator('tbody').innerText(), /synthetic-machine/);
  await page.getByRole('navigation', {name: 'Main navigation'}).getByRole('link', {name: 'Conflicts', exact: true}).click();
  assert.equal(await page.locator('tbody tr').count(), 5);
  const conflicts = await page.locator('tbody').innerText();
  assert.match(conflicts, /shorter/);
  assert.match(conflicts, /3 open copies at this path/);
  assert.match(conflicts, /from laptop/);
  await page.getByRole('link', {name: 'Open and resolved', exact: true}).click();
  assert.equal(await page.locator('tbody tr').count(), 6);
  assert.match(await page.locator('tbody').innerText(), /Head kept/);
  // Transcript viewer: a ready session, literal text, bounds, paging and deep links.
  await page.goto(live.url + '/sessions?state=ready');
  await page.locator('.session-name').first().click();
  await page.getByRole('link', {name: 'Read transcript →'}).click();
  await page.getByRole('heading', {name: 'Transcript', exact: true}).waitFor();
  assert.equal(await page.locator('.event').count(), 100);
  assert.equal(await page.evaluate(() => window.owned), undefined);
  assert.ok(await page.locator('.badge.failed', {hasText: 'tool error'}).count() > 0, 'tool error badge');
  await page.getByText(/Showing the first 32 KiB of/).waitFor();
  await page.getByText('Encrypted content is stored opaque. It is not decrypted or shown.').waitFor();
  assert.equal(await page.getByText('c3ludGhldGljLWNpcGhlcnRleHQ=').count(), 0);
  await page.screenshot({path: join(artifacts, 'transcript-desktop.png'), fullPage: false});
  const transcriptURL = page.url();
  // Copy-out: select #2, shift-click #6, copy, and read the clipboard.
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], {origin: live.url});
  await page.getByRole('checkbox', {name: 'Select event 2', exact: true}).click();
  await page.getByRole('checkbox', {name: 'Select event 6', exact: true}).click({modifiers: ['Shift']});
  await page.getByText('Events #2 to #6 selected (5).').waitFor();
  await page.getByRole('button', {name: 'Copy as text'}).click();
  await page.getByText('Copied 5 events as text.').waitFor();
  const copied = await page.evaluate(() => navigator.clipboard.readText());
  assert.match(copied, /^Excerpt from a stored /);
  assert.match(copied, /Events #2 to #6 of generation \d+\. Source: http:\/\/127\.0\.0\.1:\d+\/sessions\//);
  assert.ok(copied.indexOf('[#2 ') < copied.indexOf('[#6 ') && !copied.includes('[#7 '), 'copied span');
  const openHref = await page.getByRole('link', {name: 'Open as text'}).getAttribute('href');
  const plainText = await (await context.request.get(live.url + openHref)).text();
  assert.equal(plainText, copied);
  await page.screenshot({path: join(artifacts, 'transcript-copy.png'), fullPage: false});
  await page.getByRole('button', {name: 'Clear', exact: true}).click();
  await page.getByRole('link', {name: 'Next page'}).first().click();
  assert.equal(await page.locator('.event').first().getAttribute('id'), 'e-100');
  await page.getByRole('link', {name: 'Link to event 120'}).click();
  assert.match(page.url(), /[?&]gen=\d+&at=120#e-120$|[?&]at=120&gen=\d+#e-120$/);
  await page.waitForFunction(() => document.activeElement && document.activeElement.id === 'e-120');
  assert.equal(await page.locator('.event.target').getAttribute('id'), 'e-120');
  await page.setViewportSize({width: 390, height: 844});
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile transcript overflows');
  await page.screenshot({path: join(artifacts, 'transcript-mobile.png'), fullPage: false});
  await page.setViewportSize({width: 1440, height: 1100});
  // Search: literal text with punctuation, marked matches, a hit opens its event.
  await page.getByRole('navigation', {name: 'Main navigation'}).getByRole('link', {name: 'Search', exact: true}).click();
  await page.getByText(/Searching \d+ of \d+ ready sessions/).waitFor();
  await page.getByRole('searchbox', {name: 'Text'}).fill('remote rejected <refs');
  await page.getByRole('button', {name: 'Search', exact: true}).click();
  assert.ok(await page.locator('.hit').count() > 0, 'no search hits');
  assert.match(await page.locator('.hit mark').first().innerText(), /^remote rejected <refs$/i);
  assert.equal(await page.evaluate(() => window.owned), undefined);
  await page.screenshot({path: join(artifacts, 'search-desktop.png'), fullPage: false});
  const hitPosition = (await page.locator('.hit .pos').first().innerText()).slice(1);
  await page.locator('.hit .session-name').first().click();
  await page.waitForFunction(id => document.activeElement && document.activeElement.id === 'e-' + id, hitPosition);
  assert.match(await page.locator('.event.target .content').innerText(), /remote rejected/);
  const searchURL = live.url + '/search?q=' + encodeURIComponent('git push --dry-run');
  await page.goto(searchURL + '&harness=codex');
  assert.ok(await page.locator('.hit').count() > 0, 'no filtered hits');
  assert.equal(await page.locator('.hit .harness', {hasText: /^(terva|claude|opencode|cursor|cursor-cli)$/}).count(), 0);
  // Structured search with no text: every failed Bash result.
  await page.goto(live.url + '/search');
  await page.getByLabel('Tool', {exact: true}).fill('Bash');
  await page.getByLabel('Tool errors only').check();
  await page.getByRole('button', {name: 'Search', exact: true}).click();
  const failedHits = await page.locator('.hit').count();
  assert.ok(failedHits > 0, 'no structured hits');
  assert.equal(await page.locator('.hit .badge.failed').count(), failedHits);
  await page.goto(live.url + '/search?q=ab');
  await page.getByRole('heading', {name: 'That search cannot run'}).waitFor();
  // Activity: two charts with a table, unmeasured buckets hatched, not zero.
  await page.goto(live.url + '/activity?range=30d');
  await page.getByRole('heading', {name: 'Accepted head updates'}).waitFor();
  assert.equal(await page.locator('figure.chart svg[role=img]').count(), 2);
  assert.match(await page.locator('figure.chart svg').first().getAttribute('aria-label'), /^Accepted head updates from .+ measured buckets/);
  assert.ok(await page.locator('path.bar.negative').count() > 0, 'no shrinking bucket drawn');
  assert.ok(await page.locator('rect.unmeasured').count() > 0, 'unmeasured range not hatched');
  await page.getByText('Show as a table').click();
  assert.equal(await page.locator('.activity-table tbody tr').count(), 30);
  assert.match(await page.locator('.activity-table tbody').innerText(), /not measured/);
  await page.screenshot({path: join(artifacts, 'activity-desktop.png'), fullPage: true});
  // A refresh keeps the open table and an unsubmitted choice.
  await page.getByLabel('Harness', {exact: true}).selectOption('claude');
  await page.getByRole('button', {name: 'Refresh now'}).click();
  await page.waitForFunction(() => document.querySelector('#refresh-status').textContent.startsWith('Up to date'));
  assert.equal(await page.locator('#activity-table').evaluate(d => d.open), true, 'refresh closed the table');
  assert.equal(await page.getByLabel('Harness', {exact: true}).inputValue(), 'claude', 'refresh reset the form');
  await page.getByLabel('Harness', {exact: true}).selectOption('codex');
  await page.getByRole('button', {name: 'Show', exact: true}).click();
  await page.waitForURL(/harness=codex/);
  assert.equal(await page.getByLabel('Harness', {exact: true}).inputValue(), 'codex');
  await page.goto(live.url + '/activity?range=7d-hourly');
  assert.equal(await page.locator('.activity-table tbody tr').count(), 168);
  await page.setViewportSize({width: 390, height: 844});
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile activity overflows');
  await page.screenshot({path: join(artifacts, 'activity-mobile.png'), fullPage: true});
  let reachedRange = false;
  for (let i = 0; i < 20 && !reachedRange; i++) {
    await page.keyboard.press('Tab');
    reachedRange = await page.evaluate(() => document.activeElement.name === 'range');
  }
  assert.ok(reachedRange, 'keyboard cannot reach the activity range');
  await page.setViewportSize({width: 1440, height: 1100});
  await page.goto(live.url);
  await page.clock.install();
  let refreshes = 0;
  page.on('request', r => {if (r.headers()['x-lampi-refresh']) refreshes++;});
  await page.getByRole('button', {name: 'Refresh now'}).click();
  await page.waitForFunction(() => document.querySelector('#refresh-status').textContent.startsWith('Up to date'));
  await page.evaluate(() => {Object.defineProperty(document, 'hidden', {configurable: true, value: true}); document.dispatchEvent(new Event('visibilitychange'));});
  const before = refreshes;
  await page.clock.fastForward(30000);
  assert.equal(refreshes, before, 'hidden tab polled');
  await page.evaluate(() => {Object.defineProperty(document, 'hidden', {configurable: true, value: false}); document.dispatchEvent(new Event('visibilitychange'));});
  const response = page.waitForResponse(r => r.request().headers()['x-lampi-refresh'] === '1');
  await page.clock.fastForward(25000); await response;
  const failRefresh = async route => {
    if (route.request().headers()['x-lampi-refresh']) await route.fulfill({status: 503, contentType: 'text/plain', body: 'synthetic read failure'});
    else await route.continue();
  };
  await page.route(live.url + '/', failRefresh);
  await page.getByRole('button', {name: 'Refresh now'}).click();
  await page.waitForFunction(() => document.querySelector('#refresh-status').textContent.includes('Refresh failed'));
  await page.unroute(live.url + '/', failRefresh);
  await page.getByRole('button', {name: 'Refresh now'}).click();
  await page.waitForFunction(() => document.querySelector('#refresh-status').textContent.startsWith('Up to date'));
  await page.clock.resume();
  await page.setViewportSize({width: 390, height: 844});
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile page overflows');
  await page.screenshot({path: join(artifacts, 'overview-mobile.png'), fullPage: true});
  await page.keyboard.press('Tab');
  assert.ok(await page.evaluate(() => document.activeElement.tagName !== 'BODY'), 'keyboard focus absent');
  // Submit the real form so browser-generated Origin/referrer behavior is tested.
  // Stop the redirected GET from silently signing back in through the fake IdP.
  let redirectHandled;
  const redirected = new Promise(resolve => { redirectHandled = resolve; });
  const stopRedirect = async route => {
    await route.fulfill({status: 204});
    redirectHandled();
  };
  await page.route(live.url + '/', stopRedirect);
  const logoutResponse = page.waitForResponse(r => r.url() === live.url + '/auth/oidc/logout' && r.request().method() === 'POST');
  await page.getByRole('button', {name: 'Sign out', exact: true}).click();
  const logout = await logoutResponse;
  assert.equal(logout.status(), 303);
  assert.equal((await logout.request().allHeaders()).origin, live.url);
  assert.equal((await logout.request().allHeaders()).referer, live.url + '/');
  await redirected;
  await page.unroute(live.url + '/', stopRedirect);
  assert.equal((await context.request.get(live.url + '/api/web/v1/overview')).status(), 401);
  await page.getByRole('button', {name: 'Refresh now'}).click();
  await page.waitForFunction(() => document.querySelector('#refresh-status').textContent.includes('session has ended'));
  assert.equal(await page.getByRole('link', {name: 'Sign in again'}).isVisible(), true);
  // No-JS pages remain navigable and filterable.
  const noJS = await browser.newContext({ignoreHTTPSErrors: true, javaScriptEnabled: false});
  const basic = await noJS.newPage(); await basic.goto(live.url + '/sessions');
  await basic.getByLabel('Harness', {exact: true}).selectOption('claude');
  await basic.getByRole('button', {name: 'Apply filters'}).click();
  assert.equal(await basic.locator('tbody tr').count(), 21);
  await basic.goto(live.url + '/search');
  await basic.getByRole('searchbox', {name: 'Text'}).fill('git push --dry-run');
  await basic.getByRole('button', {name: 'Search', exact: true}).click();
  assert.equal(await basic.locator('.hit').count(), 50);
  await basic.getByRole('link', {name: 'Next page'}).first().click();
  assert.ok(await basic.locator('.hit').count() > 0, 'no-JS search paging');
  await basic.goto(transcriptURL);
  assert.equal(await basic.locator('.event').count(), 100);
  assert.equal(await basic.locator('#excerpt-bar').isVisible(), false);
  const pagePlain = await basic.getByRole('link', {name: 'This page as plain text'}).getAttribute('href');
  assert.match(await (await noJS.request.get(live.url + pagePlain)).text(), /Events #0 to #99 of generation/);
  await basic.getByRole('link', {name: 'Next page'}).first().click();
  assert.equal(await basic.locator('.event').first().getAttribute('id'), 'e-100');
  await basic.goto(live.url + '/activity');
  await basic.getByLabel('Range').selectOption('90d');
  await basic.getByRole('button', {name: 'Show', exact: true}).click();
  assert.equal(await basic.locator('figure.chart').count(), 2);
  assert.equal(await basic.locator('.activity-table tbody tr').count(), 90);
  const denied = await fixture(['--deny']);
  const denyPage = await context.newPage(); await denyPage.goto(denied.url);
  await denyPage.getByRole('heading', {name: /no lake viewer access/}).waitFor();
  const empty = await fixture(['--empty']);
  const emptyPage = await context.newPage(); await emptyPage.goto(empty.url);
  await emptyPage.getByRole('heading', {name: 'No sessions to show'}).waitFor();
  await emptyPage.goto(empty.url + '/activity');
  await emptyPage.getByRole('heading', {name: 'No accepted updates in this range'}).waitFor();
  assert.equal(await emptyPage.locator('figure.chart').count(), 2, 'empty range dropped the charts');
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({result: 'passed', evidence: artifacts, checks: ['OIDC login', '123 sessions', 'pagination', 'filters', 'details/provenance', 'conflicts', 'transcript paging/bounds/opaque/deep link', 'no-JS transcript', 'copy-out selection/clipboard/plain page', 'search literal/marks/filters/deep link/invalid', 'structured search without text', 'no-JS search paging', 'refresh/visibility/error/recovery/expiry', 'mobile', 'keyboard', 'logout', 'no-JS', 'denied group', 'empty lake', 'activity charts/table/filters/mobile/keyboard/no-JS/empty']}));
} finally {
  if (browser) await browser.close();
  await Promise.all(processes.map(proc => new Promise(resolve => {if (proc.exitCode !== null) return resolve(); proc.once('exit', resolve); proc.kill('SIGTERM');})));
  await rm(buildDir, {recursive: true, force: true});
}
